### ISSUE TITLE
파일 구조에 대한 논의

### ISSUE THREAD

**Issue by limelumo** [Wanted-Pre-Onboarding-Frontend-3/TMDB#2]
pages와 components 폴더 사용에 대해 협의를 하였으면 합니다.
오늘 세션중 멘토님께서도 얘기해주셨던 내용인데, 어떤 구조를 따를까요?

1. **첫번째 방법** (멘토님이 사용하신다고 한 방법) :
- pages - sample - components와 Sample.jsx
- components - 공통으로 쓰이는 파일들(예 : input.jsx ...)

<br>

2.  **두번째 방법** (우리가 지난 과제에 적용한 방법) : 
 - pages - sample - Sample.jsx 
 - components - sample - 관련 파일들

**Comment by ycs1m1yk** [comment]
```
📦src
 ┣ 📂components
 ┃ ┗ 📜logo.jsx
 ┣ 📂pages
 ┃ ┣ 📂SamplePage
 ┃ ┃ ┣ 📂components
 ┃ ┃ ┗📜sampleComponent.jsx
 ┃ ┗📜index.jsx
 ┣ 📜App.js
 ┗ 📜index.js
 ```
저는 위와 같은 구조를 썼습니다.

첫번째 방법에서 Sample.jsx 대신 index.jsx로 작성하는 방식입니다.

**Comment by woowsnu** [comment]
혜성님이 적어주신 방법 적용해봐도 좋을 것 같습니다! 

한 가지 궁금한 부분은 혜성님이 적어주신 방법에서 page 하위의 index.jsx가 
메인 페이지가 아니라 지난 저희 프로젝트 App.js에 적었던 라우팅 부분을 담당하게 되는 것으로 이해했는데 맞을까요?

**Comment by ycs1m1yk** [comment]
> 혜성님이 적어주신 방법 적용해봐도 좋을 것 같습니다!
> 
> 한 가지 궁금한 부분은 혜성님이 적어주신 방법에서 page 하위의 index.jsx가 메인 페이지가 아니고, 지난 저희 프로젝트 App.js에 적었던 라우팅 부분을 담당하게 되는 것으로 이해했는데 맞을까요?

App.js에 적었던 라우팅 부분을 담당한다는게 무슨 뜻일까요?

[링크](https://github.com/Wanted-Pre-Onboarding-Frontend-3/fruitte-team-3/tree/master/src/pages/productManage)를 살펴보시면 좋을것 같습니다

**Comment by woowsnu** [comment]
App.js에 들어가는 라우팅 부분은 BrowserRouter로 감싼 부분을 말한 것이고, 
이런 구조를 잘 안 써봐서 이게 pages>index.jsx에 들어가는 것인지 궁금해서 남겼었습니다!
https://github.com/Wanted-Pre-Onboarding-Frontend-3/fruitte-team-3/blob/master/src/App.js

```
📦src
 ┣ 📂components
 ┃ ┗ 📜logo.jsx
 ┣ 📂pages
 ┃ ┣ 📂SamplePage
 ┃ ┃ ┣ 📂components
 ┃ ┃ ┗📜sampleComponent.jsx
 ┃ ┗📜index.jsx  **여기에 들어갈 내용 (?)**
 ┣ 📜App.js
 ┗ 📜index.js
```

다른 프로젝트를 살펴보니 이렇게 사용하는 경우
pages > index.jsx에는 이런 내용이 들어가는군요..!

```
export { default as Home } from "./home";
export { default as CampDetail } from "./campDetail";
export { default as CampApply } from "./campApply";
export { default as Community } from "./community";
export { default as NotFound } from "./notFound";
```

**Comment by ycs1m1yk** [comment]
> App.js에 들어가는 라우팅 부분은 BrowserRouter로 감싼 부분을 말한 것이고, 이런 구조를 잘 안 써봐서 이게 pages>index.jsx에 들어가는 것인지 궁금해서 남겼었습니다! https://github.com/Wanted-Pre-Onboarding-Frontend-3/fruitte-team-3/blob/master/src/App.js
> 
> ```
> 📦src
>  ┣ 📂components
>  ┃ ┗ 📜logo.jsx
>  ┣ 📂pages
>  ┃ ┣ 📂SamplePage
>  ┃ ┃ ┣ 📂components
>  ┃ ┃ ┗📜sampleComponent.jsx
>  ┃ ┗📜index.jsx  **여기에 들어갈 내용 (?)**
>  ┣ 📜App.js
>  ┗ 📜index.js
> ```
> 
> 다른 프로젝트를 살펴보니 이렇게 사용하는 경우 pages > index.jsx에는 이런 내용이 들어가는군요..!
> 
> ```
> export { default as Home } from "./home";
> export { default as CampDetail } from "./campDetail";
> export { default as CampApply } from "./campApply";
> export { default as Community } from "./community";
> export { default as NotFound } from "./notFound";
> ```

위에 썼듯이 [링크](https://github.com/Wanted-Pre-Onboarding-Frontend-3/fruitte-team-3/tree/master/src/pages/productManage)를 보시면 제가 작업한 `src > pages > productManege > index.jsx` 코드를 확인하실 수 있습니다. ProductManege 페이지 컴포넌트를 export하고

`src > App.js` 에서 아래와 같이 import 하고 있습니다.
```js
import ProductManage from './pages/productManage';
```
페이지 폴더에서 index.jsx로 export한것은

단순히 외부에서 import할때 경로 deps를 한 단계 줄이기 위해서였습니다.

**Comment by ycs1m1yk** [comment]
아하 죄송합니다 첫 코멘트에 오타가 있었습니다ㅜㅜ

제가 의도한것은 아래와 같았습니다.
```
📦src
 ┣ 📂components
 ┃ ┗ 📜logo.jsx
 ┣ 📂pages
 ┃ ┣ 📂SamplePage
 ┃ ┃ ┣ 📂components
 ┃ ┃ ┃ ┗📜sampleComponent.jsx
 ┃ ┃ ┗📜index.jsx
 ┣ 📜App.js
 ┗ 📜index.js
 ```
 
 `pages > index.jsx` 가 아닌  `pages > SamplePage > index.jsx` 를 작성했었습니다.

**Comment by cockyb** [comment]
저는 개인적으로 파일을 찾을 때 눈으로 찾는걸 지양하고 cmd + p 로 파일이름검색을 하다보니
컴포넌트 - 페이지 관계에 대해서 생각하지 않고 디렉토리 구조를 짜왔습니다. 어디가 되든 상관은 없습니다.

다만 index.js, index.jsx에서의 컴포넌트 선언은 자제했으면 합니다 
```
📦src
 ┣ 📂pages
 ┃ ┣ 📂SamplePage
 ┃ ┃ ┣ 📂components
 ┃ ┃ ┃ ┗📜sampleComponent.jsx
 ┃ ┃ ┗📜index.jsx
...
```
```js
// index.jsx
export default SamplPage() ...
```
마찬가지로 cmp + p 파일명으로 컴포넌트를 찾다보니 index.js에 선언된 컴포넌트는 전체 검색이나 file path를 읽어봐야해서 찾기가 힘들더라구요.  오로지 해당 디렉토리에 있는 파일들 export 용으로만 사용했으면 좋겠습니다.

**Comment by cockyb** [comment]
-컴포넌트 파일명은 PascalCase

- 디렉토리의 index.js는 일단 미적용 컴포넌트의 명을 그대로 파일명으로 사용하기
